# Régression linéaire à plusieurs variables - Exercices tirés du MOOC d'Andrew Ng

## Chargement des données

Le jeu de données donne la valeur de plusieurs maisons, ainsi que leur taille (pieds carrés) et le nombre de chambres à coucher

### Chargez les données du fichier ex1data1.csv

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("data.csv")

### Visualisez les données (valeurs réelles)

Maintenant, nous avons deux 'features'. Voyez si elles ont le même ordre de grandeur

In [3]:
data

size  nb_bedrooms   price
0   2104            3  399900
1   1600            3  329900
2   2400            3  369000
3   1416            2  232000
4   3000            4  539900
5   1985            4  299900
6   1534            3  314900
7   1427            3  198999
8   1380            3  212000
9   1494            3  242500
10  1940            4  239999
11  2000            3  347000
12  1890            3  329999
13  4478            5  699900
14  1268            3  259900
15  2300            4  449900
16  1320            2  299900
17  1236            3  199900
18  2609            4  499998
19  3031            4  599000
20  1767            3  252900
21  1888            2  255000
22  1604            3  242900
23  1962            4  259900
24  3890            3  573900
25  1100            3  249900
26  1458            3  464500
27  2526            3  469000
28  2200            3  475000
29  2637            3  299900
30  1839            2  349900
31  1000            1  169900
32  2040            4  314900
33  3137            3  579900
34  1811            4  285900
35  1437            3  249900
36  1239            3  229900
37  2132            4  345000
38  4215            4  549000
39  2162            4  287000
40  1664            2  368500
41  2238            3  329900
42  2567            4  314000
43  1200            3  299000
44   852            2  179900
45  1852            4  299900
46  1203            3  239500

## Définissez quelques variables utiles

### Définissez X et y

X est maintenant une matrice de dimensions m x 2

In [4]:
X = data[['size','nb_bedrooms']].values
y = data['price'].values.reshape((-1, 1))
print(X)
print(y)

[[2104    3]
 [1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]
 [1940    4]
 [2000    3]
 [1890    3]
 [4478    5]
 [1268    3]
 [2300    4]
 [1320    2]
 [1236    3]
 [2609    4]
 [3031    4]
 [1767    3]
 [1888    2]
 [1604    3]
 [1962    4]
 [3890    3]
 [1100    3]
 [1458    3]
 [2526    3]
 [2200    3]
 [2637    3]
 [1839    2]
 [1000    1]
 [2040    4]
 [3137    3]
 [1811    4]
 [1437    3]
 [1239    3]
 [2132    4]
 [4215    4]
 [2162    4]
 [1664    2]
 [2238    3]
 [2567    4]
 [1200    3]
 [ 852    2]
 [1852    4]
 [1203    3]]
[[399900]
 [329900]
 [369000]
 [232000]
 [539900]
 [299900]
 [314900]
 [198999]
 [212000]
 [242500]
 [239999]
 [347000]
 [329999]
 [699900]
 [259900]
 [449900]
 [299900]
 [199900]
 [499998]
 [599000]
 [252900]
 [255000]
 [242900]
 [259900]
 [573900]
 [249900]
 [464500]
 [469000]
 [475000]
 [299900]
 [349900]
 [169900]
 [314900]
 [579900]
 [285900]
 [249900]
 [229900]
 [345000]
 [549000

### Initialisez theta (combien de dimensions?)

In [5]:
theta = np.zeros(X.ndim + 1).reshape((-1, 1))
print(theta)

[[0.]
 [0.]
 [0.]]


### Vérifiez les dimensions de theta et de X. Sont-elles compatibles pour implémenter la fonction d'hypothèse sous forme vectorisée?

In [6]:
print(theta.shape)

(3, 1)


In [7]:
print(X.shape)

(47, 2)


### Modifiez X en conséquence

In [8]:
X = np.insert(X, 0, 1, axis=1)
print(X)

[[   1 2104    3]
 [   1 1600    3]
 [   1 2400    3]
 [   1 1416    2]
 [   1 3000    4]
 [   1 1985    4]
 [   1 1534    3]
 [   1 1427    3]
 [   1 1380    3]
 [   1 1494    3]
 [   1 1940    4]
 [   1 2000    3]
 [   1 1890    3]
 [   1 4478    5]
 [   1 1268    3]
 [   1 2300    4]
 [   1 1320    2]
 [   1 1236    3]
 [   1 2609    4]
 [   1 3031    4]
 [   1 1767    3]
 [   1 1888    2]
 [   1 1604    3]
 [   1 1962    4]
 [   1 3890    3]
 [   1 1100    3]
 [   1 1458    3]
 [   1 2526    3]
 [   1 2200    3]
 [   1 2637    3]
 [   1 1839    2]
 [   1 1000    1]
 [   1 2040    4]
 [   1 3137    3]
 [   1 1811    4]
 [   1 1437    3]
 [   1 1239    3]
 [   1 2132    4]
 [   1 4215    4]
 [   1 2162    4]
 [   1 1664    2]
 [   1 2238    3]
 [   1 2567    4]
 [   1 1200    3]
 [   1  852    2]
 [   1 1852    4]
 [   1 1203    3]]


## Écrivez une fonction pour centrer et réduire les features

In [9]:
def featureScaleNormalize(X):
    mean = X[:,1:].mean(axis=0)
    stdev = X[:,1:].std(axis=0)
    res = (X.copy()[:,1:] - mean) / stdev
    res = np.insert(res, 0, 1, axis=1)
    return res, mean, stdev

In [10]:
X, mean, stdev = featureScaleNormalize(X)
print(mean)
print(stdev)
print(X)

[2000.68085106    3.17021277]
[7.86202619e+02 7.52842809e-01]
[[ 1.00000000e+00  1.31415422e-01 -2.26093368e-01]
 [ 1.00000000e+00 -5.09640698e-01 -2.26093368e-01]
 [ 1.00000000e+00  5.07908699e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.43677059e-01 -1.55439190e+00]
 [ 1.00000000e+00  1.27107075e+00  1.10220517e+00]
 [ 1.00000000e+00 -1.99450507e-02  1.10220517e+00]
 [ 1.00000000e+00 -5.93588523e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.29685755e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.89466782e-01 -2.26093368e-01]
 [ 1.00000000e+00 -6.44465993e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.71822042e-02  1.10220517e+00]
 [ 1.00000000e+00 -8.65999486e-04 -2.26093368e-01]
 [ 1.00000000e+00 -1.40779041e-01 -2.26093368e-01]
 [ 1.00000000e+00  3.15099326e+00  2.43050370e+00]
 [ 1.00000000e+00 -9.31923697e-01 -2.26093368e-01]
 [ 1.00000000e+00  3.80715024e-01  1.10220517e+00]
 [ 1.00000000e+00 -8.65782986e-01 -1.55439190e+00]
 [ 1.00000000e+00 -9.72625673e-01 -2.26093368e-01]
 [ 1.00000000e+00  7

### Maintenant nous allons devoir adapter nos fonctions _predict_, _fit_, et _cost_ à une situation à plusieurs variables

In [11]:
def predict(X, theta):
    return np.dot(X, theta)

In [12]:
def cost(X, y, theta):
    return np.sum((predict(X, theta) - y)**2) / 2 / X.shape[0]


In [13]:
def fit_with_cost(X, y, theta, alpha, num_iters):
    J_history = list()
    coef = alpha / X.shape[0]
    theta = theta.copy()
    for i in range(num_iters):
        J_history.append(cost(X, y, theta))
        diff = predict(X, theta) - y
        prevtheta = theta.copy()
        theta -= coef * np.dot(X.T, diff)
        if (prevtheta == theta).all():
            break    
    return theta, np.array(J_history), i

## Lancez l'entrainement du modèle

Vous êtes libres de choisir alpha et num_iters cette fois!

In [14]:
theta2, J_history, nb_iterations = fit_with_cost(X, y, theta, 0.0001, 5000000)
print("Nombre d'itérations : ", nb_iterations)
print(theta2)
print(J_history)



Nombre d'itérations :  643631
[[340412.65957418]
 [109447.79646953]
 [ -6578.3548541 ]]
[6.55915481e+10 6.55785428e+10 6.55655402e+10 ... 2.04328005e+09
 2.04328005e+09 2.04328005e+09]


## Visualisez l'évolution du coût (graphe de convergence)

In [15]:
import matplotlib.pyplot as plt

#fit = plt.figure()
#ax = plt.axes()
#ax.plot(J_history)

L = np.array([np.random.randint(500, 4000, 50), np.random.randint(1, 5, 50)])
L = (L - mean.reshape(-1, 1)) / stdev.reshape(-1, 1)
L = np.insert(L, 0, 1, axis=0)
L = L.T
print(L)


#print(predict(L, theta2))

plt.title("Matplotlib demo") 
plt.plot(L, predict(L, theta2), 'bo')
plt.show()

[[ 1.          0.01185337 -1.5543919 ]
 [ 1.         -0.63937825 -0.22609337]
 [ 1.         -0.05174347  1.10220517]
 [ 1.          1.73278378 -0.22609337]
 [ 1.         -0.52744781  1.10220517]
 [ 1.          0.50282095 -0.22609337]
 [ 1.          2.32041856  1.10220517]
 [ 1.          2.34712923 -1.5543919 ]
 [ 1.         -0.66990473 -1.5543919 ]
 [ 1.          1.40208023 -0.22609337]
 [ 1.          0.36417985  1.10220517]
 [ 1.          1.20874585  1.10220517]
 [ 1.         -0.55415848 -2.88269044]
 [ 1.          1.49747549 -1.5543919 ]
 [ 1.         -1.83245491  1.10220517]
 [ 1.          2.18304939 -2.88269044]
 [ 1.         -1.32368021 -0.22609337]
 [ 1.          2.0622154  -0.22609337]
 [ 1.         -0.42060513 -0.22609337]
 [ 1.          0.46339091 -2.88269044]
 [ 1.         -1.56280432  1.10220517]
 [ 1.          1.04975375 -1.5543919 ]
 [ 1.          2.26445334 -0.22609337]
 [ 1.          0.73940119 -2.88269044]
 [ 1.         -1.2575395   1.10220517]
 [ 1.         -0.21963912

<Figure size 640x480 with 1 Axes>

## Testez votre modèle

Que vaut une maison de 1650 pieds carrés et de 3 chambres à coucher? (Si la valeur est aberrante, vous avez peut-être oublié une étape...)

In [16]:
test = np.array([1650, 3])
test = (test - mean) / stdev
test = np.insert(test, 0, 1, axis=0)
print(predict(test, theta2))

[293081.46433464]


### Réécrivez votre fonction fit pour qu'elle prenne en compte un parametre de regularisation (L1, L2 pour Lasso ou Ridge) et adapte la mise  a jour de theta an fonction de la regularization précisée

In [17]:
def fit_with_regularization(X, y, theta, alpha, num_iters, regularization=""):
    J_history = list()
    coef = alpha / X.shape[0]
    reg = 25000 / X.shape[0]
    theta = theta.copy()
    L1 = 1 if regularization == "L1" else 0
    L2 = 1 if regularization == "L2" else 0
    for i in range(num_iters):
        J_history.append(cost(X, y, theta))
        diff = predict(X, theta) - y
        prevtheta = theta.copy()
        Ltheta = np.insert(theta[1:,0], 0, 0).reshape(3, 1)
        theta -= coef * (np.dot(X.T, diff)
                        + (L1 * reg * np.abs(Ltheta.copy()))
                        + (L2 * reg * Ltheta.copy()**2))
        if (prevtheta == theta).all():
            break    
    return theta, np.array(J_history), i

In [18]:
theta3, J_history2, ite = fit_with_regularization(X, y, theta, 0.001, 1000000, "")
print("iter : ", ite)
print(theta3)
print(J_history2)
theta3, J_history2, ite = fit_with_regularization(X, y, theta, 0.001, 1000000, "L1")
print("iter : ", ite)
print(theta3)
print(J_history2)
theta3, J_history2, ite = fit_with_regularization(X, y, theta, 0.001, 1000000, "L2")
print("iter : ", ite)
print(theta3)
print(J_history2)

#[[340412.65957418]
# [109447.79646953]
# [ -6578.3548541 ]]
#[6.55915481e+10 6.55785428e+10 6.55655402e+10 ... 2.04328005e+09
# 2.04328005e+09 2.04328005e+09]

iter :  69572
[[340412.65957444]
 [109447.79646963]
 [ -6578.35485415]]
[6.55915481e+10 6.54615565e+10 6.53318377e+10 ... 2.04328005e+09
 2.04328005e+09 2.04328005e+09]
iter :  29960
[[340412.65957444]
 [  8402.04817389]
 [  4059.63932071]]
[6.55915481e+10 6.54615565e+10 6.53319977e+10 ... 6.60306290e+09
 6.60306290e+09 6.60306290e+09]
iter :  999999
[[3.40412660e+05]
 [4.91443626e+01]
 [6.94004988e+01]]
[6.55915481e+10 6.54615565e+10 6.53470490e+10 ... 7.63388820e+09
 7.64216970e+09 7.63388820e+09]


### La fonction fit au complet. Ajoutez un dernier parametre qui précise le gradient employé (stochastic, mini_batch(avec le batch_size), batch). Pour la descente de gradient stochastic et minibatch on met a jour le learning rate avec la formule du learning rate decay

In [69]:
def complete_fit(X, y, theta, alpha, num_iters, regularization="", gradient_descent="batch", batch_size=4, decay_rate=1):
    J_history = list()
    theta = theta.copy()

    L1 = 1 if regularization == "L1" else 0
    L2 = 1 if regularization == "L2" else 0

    if gradient_descent == "batch":
        batch_size = X.shape[0]
    elif gradient_descent == "stochastic":
        batch_size = 1

    j = 0
    k = batch_size    
    reg = 25000 / batch_size

    for i in range(num_iters):
        alpha /= (1 + (decay_rate * i))
        coef = alpha / batch_size
        J_history.append(cost(X, y, theta))
        diff = predict(X[j:k,:], theta) - y[j:k,:]
        prevtheta = theta.copy()
        Ltheta = np.insert(theta[1:,0], 0, 0).reshape(3, 1)
        theta -= coef * (np.dot(X[j:k,:].T, diff)
                        + (L1 * reg * np.abs(Ltheta.copy()))
                        + (L2 * reg * Ltheta.copy()**2))
        j = k % X.shape[0]
        k = min(k + batch_size, X.shape[0]) if k < X.shape[0] else batch_size
        #if (prevtheta == theta).all():
        #    break    
    return theta, np.array(J_history), i

In [71]:
theta4, J_history3, ite = complete_fit(X, y, theta, 0.001, 1000000, "L1")
print("iter : ", ite)
print(theta4)
print(J_history3)

theta4, J_history3, ite = complete_fit(X, y, theta, 0.001, 1000000, "L1", "mini_batch", 5)
print("iter : ", ite)
print(theta4)
print(J_history3)

theta4, J_history3, ite = complete_fit(X, y, theta, 0.001, 1000000, "L1", "stochastic")
print("iter : ", ite)
print(theta4)
print(J_history3)

# iter :  999999
# [[584.64018953]
#  [180.61935402]
#  [ 93.39317681]]
# [6.55915481e+10 6.54615565e+10 6.53967601e+10 ... 6.53685177e+10
#  6.53685177e+10 6.53685177e+10]
# iter :  999999
# [[583.59542504]
#  [ 60.90430853]
#  [ 70.05469551]]
# [6.55915481e+10 6.54520294e+10 6.54216064e+10 ... 6.53827877e+10
#  6.53827877e+10 6.53827877e+10]
# iter :  999999
# [[   640.37780806]
#  [ -9051.85541345]
#  [-16731.03185315]]
# [6.55915481e+10 6.54548881e+10 6.55426207e+10 ... 6.75121942e+10
#  6.75121942e+10 6.75121942e+10]

iter :  999999
[[584.64018953]
 [180.61935402]
 [ 93.39317681]]
[6.55915481e+10 6.54615565e+10 6.53967601e+10 ... 6.53685177e+10
 6.53685177e+10 6.53685177e+10]
iter :  999999
[[583.59542504]
 [ 60.90430853]
 [ 70.05469551]]
[6.55915481e+10 6.54520294e+10 6.54216064e+10 ... 6.53827877e+10
 6.53827877e+10 6.53827877e+10]
iter :  999999
[[   640.37780806]
 [ -9051.85541345]
 [-16731.03185315]]
[6.55915481e+10 6.54548881e+10 6.55426207e+10 ... 6.75121942e+10
 6.75121942e+10 6.75121942e+10]
